export const ActionTypes = {
    ADD_TO_CART:'ADD_TO_CART',
    REMOVE_FROM_CART:'REMOVE_FROM_CART',
    GET_CART_ITEMS_COUNT:'GET_CART_ITEMS_COUNT',
    SET_SIMILAR_COURSES:'SET_SIMILAR_COURSES',
    SET_CURRENT_COURSE:'SET_CURRENT_COURSE',
    UPDATE_USER_INFO:'UPDATE_USER_INFO'
}